---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: dummy0
spec:
  selectors:
  - cel:
      expression: device.driver == "kubecon-na-2025-knd.example.com"
  - cel:
      expression: device.attributes["kubecon-na-2025-knd.example.com"].interfaceName == "dummy0"